### ISSUE TITLE
Why are my labels and relationships prefixed by a "2"?

### ISSUE THREAD

**Issue by flowt-au** [FalkorDB/falkordb-browser#509]
I have just discovered this great tool! Thank you. :-) (I was using RedisInsight before now. )

I notice the labels and relationships are all prefixed by a "2" as per this screenshot. My labels are eg `m000` but in the UI they are `2m000`.
![Greenshot 2024-10-10 06 57 27](https://github.com/user-attachments/assets/a330e6ff-2fba-4568-b80b-8e01fe1559cd)

What does the "2" signify?

I am using the "edge" version via the docker command.

Thanks again!
Murray

**Comment by Anchel123** [comment]
how do you run the browser instance ?

**Comment by flowt-au** [comment]
I am starting falkor via docker-compose as below. As I was replying I realised your docs say to use the "edge" version and I was using the "v4.3.0" version! So I restarted using "edge" and all works as expected now. Sorry about that!

```
  falkor:
    # image: falkordb/falkordb:v4.3.0 # The "2" appears on this one.

    image: falkordb/falkordb:edge # but not on this one

    container_name: flowt-central-falkor

    volumes:
      - falkor_data:/data

    environment:
      REDIS_ARGS: "--appendonly yes --dir /data --dbfilename dump.rdb"

    ports:
      - "6379:6379"
      - "3000:3000"
```
Not sure if I need the REDIS_ARGS section any more?

Anyway, then: `http://localhost:3000/`.
