### ISSUE TITLE
Dependent Bot should monitor the github-actions deps too 

### ISSUE THREAD

**Issue by gkorland** [FalkorDB/falkordb-browser#97]
```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

```
